ARG ERIC_ENM_MODELS_IMAGE_REPO=armdocker.rnd.ericsson.se/proj-enm
ARG ERIC_ENM_MODELS_IMAGE_NAME=eric-enm-models-base-image
ARG ERIC_ENM_MODELS_IMAGE_TAG=1.64.0-34

FROM ${ERIC_ENM_MODELS_IMAGE_REPO}/${ERIC_ENM_MODELS_IMAGE_NAME}:${ERIC_ENM_MODELS_IMAGE_TAG}